// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Int_Input.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Text_Display.H>
#include <Fl/Fl_PNG_Image.H>
#include <Fl/Fl_Image.H>

class UserInterface {
public:
  UserInterface();
protected:
  Fl_PNG_Image* myimage;
  Fl_Box *boxImg;
  Fl_Double_Window *w;
  Fl_Int_Input *inputQuant;
  Fl_Box *boxVencedor;
  Fl_Button *btnReset;
  Fl_Button *btnSortear;
public:
  Fl_Text_Display *qntPartText;
protected:
  Fl_Box *boxNoGanhador;
};
#endif
