// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "window.h"

UserInterface::UserInterface() {
  { w = new Fl_Double_Window(400, 600, "AddSub");
    w->box(FL_EMBOSSED_BOX);
    w->user_data((void*)(this));
    { inputQuant = new Fl_Int_Input(65, 329, 140, 41);
      inputQuant->type(2);
      inputQuant->labelsize(20);
      inputQuant->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Int_Input* inputQuant
    { boxVencedor = new Fl_Box(65, 423, 265, 67);
      boxVencedor->box(FL_DOWN_BOX);
      boxVencedor->labelsize(28);
    } // Fl_Box* boxVencedor
    { btnReset = new Fl_Button(215, 329, 113, 41, "Reset");
    } // Fl_Button* btnReset
    { btnSortear = new Fl_Button(65, 510, 265, 40, "Sortear");
    } // Fl_Button* btnSortear
    { qntPartText = new Fl_Text_Display(185, 330, 25, 25, "Quantia de Participantes");
      qntPartText->box(FL_NO_BOX);
      qntPartText->labelsize(24);
    } // Fl_Text_Display* qntPartText
    { boxNoGanhador = new Fl_Box(85, 376, 225, 39);
      boxNoGanhador->labelsize(28);
    } // Fl_Box* boxNoGanhador
    w->end();
  } // Fl_Double_Window* w
}
